export const PAISES = [

    "Argentina",
    "Aruba",
    "Australia",
    "Austria",
    "Bahamas (the)",
    "Bahrain",
    "Belgium",
    "Belize",
    "Brazil",
    "Bulgaria",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Czechia",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Finland",
    "France",
    "Germany",
    "Ghana",
    "Greece",
    "Greenland",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Ireland",
    "Italy",
    "Jamaica",
    "Japan",
    "Luxembourg",
    "Malaysia",
    "Maldives",
    "Mexico",
    "Monaco",
    "New Zealand",
    "Nicaragua",
    "Norway",
    "Panama",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Thailand",
    "Turkey",
    "United States of America",
    "Uruguay",
    "Venezuela",
  ];